{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.traefik.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "lldap-chart.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  entryPoints: {{ .Values.ingress.traefik.entryPoints.http }}
  routes:
  {{- range .Values.ingress.hosts }}
    - match: Host(`{{ .host }}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ include "lldap-chart.fullname" $ }}-service
          port: 17170
  {{- end }}
  tls: {{ .Values.ingress.traefik.tls | toYaml }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "lldap-chart.fullname" . }}-ingress-ldap
  namespace: {{ .Values.namespace }}
spec:
  entryPoints: {{ .Values.ingress.traefik.entryPoints.ldaps }}
  routes:
  {{- range .Values.ingress.hosts }}
    - match: HostSNI(`{{ .host }}`)
      services:
        - name: {{ include "lldap-chart.fullname" $ }}-service
          port: 3890
          tls: true
  {{- end }}
  tls: {{ .Values.ingress.traefik.tls | toYaml }}
{{- else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lldap-chart.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- if .Values.ingress.labels }}
  labels:
    {{ toYaml .Values.ingress.labels | indent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "lldap-chart.fullname" $ }}-service
                port:
                  number: 17170
        {{- end }}
  {{- end }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
{{- end }}
